<?php
/*---------------- General ----------------------------*/
$koje_label['LBL_ADMIN']                = '';
$koje_label['BTN_EDIT']                 = 'Edit';
$koje_label['BTN_BACK_TO_LIST']         = 'Back To List';
$koje_label['BTN_DETAIL']               = 'Detail';
$koje_label['BTN_CANCEL']               = 'Cancel';
$koje_label['BTN_LOG']                  = 'Log Activity';
$koje_label['BTN_PRINT_PDF']            = 'Print';
$koje_label['BTN_CANVASING']            = 'Canvasing';
$koje_label['BTN_DOCUMENT']            	= 'Documents';
$koje_label['BTN_PROSPECT']            	= 'Prospect';
$koje_label['_KOJE_PICK_']              = 'Pick';

$koje_label['sys_created_name']         = 'Created By';
$koje_label['sys_created_date']         = 'Created Date';
$koje_label['status']                   = 'Status';
$koje_label['type']                     = 'Type';
$koje_label['description']              = 'Description';
$koje_label['select_none']              = '-';

$koje_label['jan_01']                   = 'January';
$koje_label['feb_02']                   = 'February';
$koje_label['mar_03']                   = 'March';
$koje_label['apr_04']                   = 'April';
$koje_label['may_05']                   = 'May';
$koje_label['jun_06']                   = 'June';
$koje_label['jul_07']                   = 'July';
$koje_label['aug_08']                   = 'August';
$koje_label['sep_09']                   = 'September';
$koje_label['oct_10']                   = 'October';
$koje_label['nov_11']                   = 'November';
$koje_label['dec_12']                   = 'December';

/* --------------- Button ------------------ */
$koje_label['BTN_STAGE']                = 'Stage';
$koje_label['BTN_TELEMARKETING']        = 'Telemarketing';
$koje_label['BTN_NEXT_STAGE']           = 'Next Stage...';
$koje_label['BTN_PROPOSAL']             = 'Proposal';
$koje_label['BTN_PRESENTATION']         = 'Presentation';
$koje_label['BTN_SURVEY']               = 'Survey';
$koje_label['BTN_REQUIREMENT']          = 'Requirement';
$koje_label['BTN_QUOTATION']            = 'Quotation';
$koje_label['BTN_REQ_APPROVAL']         = 'Request Approval';
$koje_label['BTN_APPROVAL']             = 'Approval';
$koje_label['BTN_NEGOTIATION']          = 'Negotiation';
$koje_label['BTN_NEGOTIATE']            = 'Negotiate';
$koje_label['BTN_QUOTATION_ITEM']       = 'Quotation Detail';
$koje_label['BTN_GENERATE_BILLING']     = 'Generate Billing';
$koje_label['BTN_EDIT_PROFILE']         = 'Edit Profile';
$koje_label['BTN_SAVE_ADDROW']          = 'Save & Add Row';
$koje_label['BTN_UPLOAD_DOC']          	= 'Add Document';
$koje_label['BTN_DELETE']        		= 'Delete';
$koje_label['BTN_PROCESS']              = 'Process';
$koje_label['BTN_DEAL']                 = 'Deal';
$koje_label['BTN_LEVEL_UP'] 			= 'Level Up';
$koje_label['BTN_VERIFICATION']			= 'Verification';

/* --------------- title ------------------ */
$koje_label['group_reference']          = 'Group Reference';
$koje_label['sales_id']                 = 'Sales';
$koje_label['prospect_no']              = 'Prospect No.';
$koje_label['prospect_name']            = 'Prospect Name';
$koje_label['prospect_type']            = 'Prospect Type';
$koje_label['company_name']             = 'Company Name';
$koje_label['company_phone']            = 'Phone';
$koje_label['company_npwp']             = 'NPWP';
$koje_label['company_anniversary']      = 'Anniversary';
$koje_label['company_address_info']     = 'Address Info';
$koje_label['start_date']               = 'Start Date';
$koje_label['end_date']                 = 'End Date';
$koje_label['stage_name']               = 'Stage';
$koje_label['prospect_start_date']      = 'Start Date';
$koje_label['cancel_reason']            = 'Cancel Reason';
$koje_label['cancel_notes']             = 'Cancel Notes';
$koje_label['address_street']           = 'Street';
$koje_label['address_city_id']          = 'City';
$koje_label['address_city']             = 'City';
$koje_label['address_province']         = 'Province';
$koje_label['address_zip']              = 'Zip';
$koje_label['target_closed_date']       = 'Target Closed Date';
$koje_label['target_amount']            = 'Target Amount';
$koje_label['probability']              = 'Probability';
$koje_label['probability_pcts']         = 'Probability';
$koje_label['address_area']             = 'Area';
$koje_label['source']                   = 'Source';
$koje_label['d_segmentation']           = 'Line Of Business';
$koje_label['d_customer_group']         = 'Group';
$koje_label['customer_group']           = 'Group';
$koje_label['cp_1_salute']              = 'Salute';
$koje_label['cp_1_name']                = 'Name';
$koje_label['cp_1_email']               = 'Email';
$koje_label['cp_1_department']          = 'Department';
$koje_label['cp_1_mobile']              = 'Mobile';
$koje_label['cp_1_info']                = 'Info';
$koje_label['cp_2_salute']              = 'Salute';
$koje_label['cp_2_name']                = 'Name';
$koje_label['cp_2_department']          = 'Department';
$koje_label['cp_2_mobile']              = 'Mobile';
$koje_label['cp_2_email']               = 'Email';
$koje_label['cp_2_info']                = 'Info';
$koje_label['notes']                    = 'Notes';
$koje_label['send_by']                  = 'Send By';
$koje_label['proposal_status']          = 'Proposal Status';
$koje_label['business_info']            = 'Business Info';
$koje_label['technical_info']           = 'Technical Info';
$koje_label['attachment_1']             = 'Attachment #1';
$koje_label['attachment_2']             = 'Attachment #2';
$koje_label['attachment_3']             = 'Attachment #3';
$koje_label['attachment_1_id']         = 'New Attachment #1';
$koje_label['attachment_2_id']         = 'New Attachment #2';
$koje_label['attachment_3_id']         = 'New Attachment #3';
$koje_label['submit_proposal_date']    = 'Submit Date';
$koje_label['response_info']           = 'Response Info';
$koje_label['title']                   = 'Title';
$koje_label['expired_date']            = 'Expired Date';
$koje_label['quotation_no']             = 'Quotation No.';
$koje_label['result_info']              = 'Result Info';
$koje_label['t_quotation_log_id']       = 'ID';
$koje_label['submitted_date']           = 'Submitted Date';
$koje_label['submitted_notes']          = 'Submitted Notes';
$koje_label['request_notes']           = 'Request Notes';
$koje_label['approved_notes']           = 'Approval Notes';
$koje_label['ALERT_NEED_APPROVED']      = '<b><font color=red>Permintaan ditolak. Ada QUOTATION yang belum di approved. Pastikan semua data sudah di approved atau di cancel.</font></b>';
$koje_label['contact_name']             = 'Contact Name';
$koje_label['name']                     = 'Name';
$koje_label['response']                 = 'Response';
$koje_label['response_date']            = 'Response Date';
$koje_label['ALERT_NEED_CLARRIFICATION']= '<b><font color=red>Permintaan ditolak. Ada Permintaan CLARRIFICATION yang belum finish. Pastikan semua data sudah di selesaikan atau di cancel.</font></b>';
$koje_label['contact_position']         = 'Contact Position';
$koje_label['approver_name']            = 'Approver Name';
$koje_label['approver_position']        = 'Approver Position';
$koje_label['ALERT_NEED_CONTRACT']= '<b><font color=red>Permintaan ditolak. Ada Data CONTRACT yang belum finish. Pastikan semua data sudah di selesaikan atau di cancel.</font></b>';
$koje_label['ALERT_NEED_IMPLEMENTATION']= '<b><font color=red>Permintaan ditolak. Ada Data IMPLEMENTATION yang belum finish. Pastikan semua data sudah di selesaikan atau di cancel.</font></b>';
$koje_label['install_address_name']             = 'Address Name';
$koje_label['install_address_street']           = 'Install Address Street';
$koje_label['install_address_city_id']          = 'Install Address City';
$koje_label['install_address_zip']              = 'Install Address Zip';
$koje_label['install_address_country']          = 'Install Address Country';
$koje_label['assign_to']                        = 'Assign To';
$koje_label['activity_date']                    = 'Activity Date';
$koje_label['service_lists']                    = 'Service List';
$koje_label['sum_amount']                       = 'Total Amount';
$koje_label['sum_amount_deal']                  = 'Total Deal';
$koje_label['product_name']                     = 'Product Name';
$koje_label['company_curr_service']             = 'Service';
$koje_label['company_curr_provider']            = 'Provider';
$koje_label['company_curr_expense']             = 'Expense';
$koje_label['t_product_service_id']             = 'Service';
$koje_label['speed']                            = 'Speed Capacity';
$koje_label['uom']                              = 'Speed Unit';
$koje_label['no_quotation']                     = "No Quotation Approved. Check Quotation.";
$koje_label['no_quotation_deal']                = "No Quotation Deal. Check Negotiation.";
$koje_label['customer_response']                = 'Customer Response';
$koje_label['target_date']                      = 'Target Date';
$koje_label['survey_date']                      = 'Survey Date';
$koje_label['survey_notes']                     = 'Survey Notes';
$koje_label['escalation_notes']                 = 'Escalation Notes';
$koje_label['duration_days']                    = 'Duration Days';
$koje_label['prospect_start_date_fmt']          = 'Prospect Start Date';
$koje_label['start_date_fmt']                   = 'Start Date';
$koje_label['sales_name']                       = 'Sales Name';

$koje_label['conn_distance']                    = 'Distance';
$koje_label['conn_capacity']                    = 'Capacity';
$koje_label['conn_port']                        = 'Port';
$koje_label['conn_info']                        = 'Others Info';
$koje_label['conn_recommendation']              = 'Recommendation';

$koje_label['mgsrv_info_1']                     = 'Info 1';
$koje_label['mgsrv_info_2']                     = 'Info 2';
$koje_label['mgsrv_info_3']                     = 'Info 3';
$koje_label['mgsrv_info_4']                     = 'Info 4';
$koje_label['mgsrv_recommendation']             = 'Recommendation';

$koje_label['other_name']                       = 'Service Name';
$koje_label['other_info_1']                     = 'Info 1';
$koje_label['other_info_2']                     = 'Info 2';
$koje_label['other_info_3']                     = 'Info 3';
$koje_label['other_info_4']                     = 'Info 4';
$koje_label['other_recommendation']             = 'Recommendation';

$koje_label['vicon_info_1']                     = 'Info 1';
$koje_label['vicon_info_2']                     = 'Info 2';
$koje_label['vicon_info_3']                     = 'Info 3';
$koje_label['vicon_info_4']                     = 'Info 4';
$koje_label['vicon_recommendation']             = 'Recommendation';

$koje_label['dc_info_1']                     = 'Info 1';
$koje_label['dc_info_2']                     = 'Info 2';
$koje_label['dc_info_3']                     = 'Info 3';
$koje_label['dc_info_4']                     = 'Info 4';
$koje_label['dc_recommendation']             = 'Recommendation';
$koje_label['t_order_type_id']               = 'Order Type';
$koje_label['account_no']                    = 'Account No.';  
$koje_label['product_name_order']            = 'Product Name'; 

$koje_label['d_uom']                    = 'Unit of Measure';
$koje_label['contract_length']          = 'Contract Length (Month)';
$koje_label['agreed_sla']               = 'Agreed SLA (%)';
$koje_label['d_trial_status']           = 'Trial Status';
$koje_label['trial_days']               = 'Trial Days';
$koje_label['delivery_days']            = 'Delivery Days';


$koje_label['doc_type']                 = 'Document Type';
$koje_label['doc_no']                   = 'Document No';
$koje_label['doc_date']                 = 'Document Date';
$koje_label['t_file_id']                = 'File';
$koje_label['file_name']                = 'File Name';


$koje_label['presales_status'] = 'Presales Status';
$koje_label['presales_desc'] = 'Presales Description';
$koje_label['presales_update'] = 'Presales Update Date';